services:
  base:
    build:
      context: ./mlflow
      dockerfile: Dockerfile.base
    image: ${COMPOSE_PROJECT_NAME?Variable not set}/base:local
    deploy:
      replicas: 0

  mlflow:
    depends_on:
      - base
    build:
      context: ./mlflow
      dockerfile: Dockerfile.mlflow
      args:
        - "BASE_IMAGE=${COMPOSE_PROJECT_NAME?Variable not set}/base:local"
        - "MLFLOW_BACKEND_URI=${MLFLOW_BACKEND_URI?Variable not set}"
        - "MLFLOW_ARTIFACTS_URI=${BASE_DIR}/mlruns"
    image: mlflow_server
    container_name: mlflow_server
    ports:
      - "${MLFLOW_PORT:-5000}:5000"
    volumes:
      - ${BASE_DIR}/mlruns:${BASE_DIR}/mlruns"
    # infinite loop
    # command: "tail -f /dev/null"